"""Compact semilocal tile contractions on one fixed quadrature/mask branch.

Scalar functional derivatives and ingredient pullbacks are generated by the
existing Graph. This module owns their AO contractions, including response
and explicit geometry sources; it owns no SCF/response solver or AO^4 kernel.
"""

import typing
from dataclasses import dataclass

import numpy as np

from generativeqc_compiler.common.arrays import immutable
from generativeqc_compiler.dft.ao import directional_ao_jets, jet_indices
from generativeqc_compiler.dft.features import (
    _density_features_from_spin_densities,
    density_features,
    spin_densities,
)

from .coefficients import coefficient_program, jet_pullback_program
from .contracts import DerivativeRequest, DiscreteEnergyContract
from .potential import assemble_coefficients, assemble_coefficients_directional
from .program import build_program
from .spec import UnsupportedXC


def _pack(spec: typing.Any, features: typing.Any) -> typing.Any:
    """Use the existing scalar ABI without evaluating unused sigma/tau reductions.

    Zero placeholders occupy inactive ABI slots only. The typed functional
    contract proves that the requested energy/derivatives do not depend on
    those slots; unsupported physical derivatives are never filled with zeros.
    """
    missing = set(spec.ingredients) - set(features)
    if missing:
        raise ValueError(f"missing active XC ingredients: {sorted(missing)}")
    rho = features["rho"]
    result = np.zeros((len(spec.features), rho.shape[1]))
    if spec.spin == "polarized":
        result[:2] = rho
        if "sigma" in features:
            result[2:5] = features["sigma"]
        if "tau" in features:
            result[5:7] = features["tau"]
    else:
        result[0] = rho.sum(axis=0)
        if "sigma" in features:
            aa, ab, bb = features["sigma"]
            result[1] = aa + 2 * ab + bb
        if "tau" in features:
            result[2] = features["tau"].sum(axis=0)
    return result


def _functional_gradient(spec: typing.Any, features: typing.Any) -> typing.Any:
    gradient = features.get("gradient")
    return (
        gradient
        if gradient is None or spec.spin == "polarized"
        else gradient.sum(axis=0)
    )


def _weighted_energy(weights: typing.Any, values: typing.Any) -> typing.Any:
    """Reject overflow in quadrature even when every scalar point is finite."""
    with np.errstate(over="ignore", invalid="ignore"):
        energy = float(weights @ values)
    if not np.isfinite(energy):
        raise ArithmeticError("nonfinite integrated XC energy")
    return energy


def _response_features(reference: typing.Any, linear: typing.Any) -> typing.Any:
    """Differentiate nonlinear sigma at the reference, keeping linear fields."""
    result = dict(linear)
    if "gradient" in linear:
        g, dg = reference["gradient"], linear["gradient"]
        result["sigma"] = immutable(
            np.stack(
                [
                    np.sum(g[a] * dg[b] + dg[a] * g[b], axis=1)
                    for a, b in ((0, 0), (0, 1), (1, 1))
                ]
            )
        )
    return result


def density_feature_response(
    jets: typing.Any, density: typing.Any, delta_density: typing.Any
) -> typing.Any:
    """Legacy full-feature response adapter with one common scientific owner.

    The semilocal contraction consumer below prunes tau and LDA gradients;
    this diagnostic helper preserves the existing full feature API.
    """
    reference = density_features(jets, density, ingredients=("gradient",))
    linear = density_features(
        jets, delta_density, ingredients=("rho", "gradient", "tau")
    )
    return _response_features(reference, linear)


def _ao_bilinear(
    left: typing.Any, density: typing.Any, right: typing.Any
) -> typing.Any:
    """Contract one pointwise AO bilinear without materializing AO-pair data."""
    return np.einsum("pi,ij,pj->p", left, density, right, optimize=True)


def _geometry_feature_direction(
    reference: typing.Any,
    jets: typing.Any,
    directional_jets: typing.Any,
    density: typing.Any,
    delta_density: typing.Any,
    family: typing.Any,
) -> typing.Any:
    """Return one LDA/GGA feature JVP from geometry plus an optional delta-D."""
    if family not in ("lda", "gga"):
        raise UnsupportedXC("XC geometry JVP supports semilocal LDA/GGA only")
    nao = np.asarray(jets).shape[2]
    d = spin_densities(density, nao)
    dd = spin_densities(delta_density, nao)
    npoint = np.asarray(jets).shape[1]
    rho = np.zeros((2, npoint))
    gradient = np.zeros((2, npoint, 3)) if family == "gga" else None
    p, dp = jets[0], directional_jets[0]
    for spin in range(2):
        ds, dds = d[spin], dd[spin]
        rho[spin] = (
            _ao_bilinear(dp, ds, p) + _ao_bilinear(p, ds, dp) + _ao_bilinear(p, dds, p)
        )
        if family == "lda":
            continue
        assert gradient is not None
        for axis in range(3):
            row = axis + 1
            pk, dpk = jets[row], directional_jets[row]
            gradient[spin, :, axis] = (
                _ao_bilinear(dpk, ds, p)
                + _ao_bilinear(pk, ds, dp)
                + _ao_bilinear(dp, ds, pk)
                + _ao_bilinear(p, ds, dpk)
                + _ao_bilinear(pk, dds, p)
                + _ao_bilinear(p, dds, pk)
            )
    result = {"rho": immutable(rho)}
    if family == "gga":
        assert gradient is not None
        result["gradient"] = immutable(gradient)
        base_gradient = reference["gradient"]
        pairs = ((0, 0), (0, 1), (1, 1))
        result["sigma"] = immutable(
            np.stack(
                [
                    np.sum(
                        gradient[a] * base_gradient[b] + base_gradient[a] * gradient[b],
                        axis=1,
                    )
                    for a, b in pairs
                ]
            )
        )
    return result


def _geometry_feature_directions(
    reference: typing.Any,
    jets: typing.Any,
    left_jets: typing.Any,
    right_jets: typing.Any,
    mixed_jets: typing.Any,
    density: typing.Any,
    delta_density: typing.Any,
    family: typing.Any,
) -> typing.Any:
    """Return left/right/mixed LDA/GGA feature directions.

    The right direction includes the supplied density response. The mixed
    direction differentiates the left fixed-density geometry source under that
    right geometry+density perturbation. Only first and second XC feature
    derivatives are needed; no third XC derivative enters a Hessian bilinear.
    """
    if family not in ("lda", "gga"):
        raise UnsupportedXC("mixed XC geometry supports semilocal LDA/GGA only")
    nao = np.asarray(jets).shape[2]
    d = spin_densities(density, nao)
    dd = spin_densities(delta_density, nao)
    npoint = np.asarray(jets).shape[1]
    left_rho = np.zeros((2, npoint))
    right_rho = np.zeros_like(left_rho)
    mixed_rho = np.zeros_like(left_rho)
    left_gradient = np.zeros((2, npoint, 3)) if family == "gga" else None
    right_gradient = np.zeros_like(left_gradient) if family == "gga" else None
    mixed_gradient = np.zeros_like(left_gradient) if family == "gga" else None

    p, lp, rp, mp = jets[0], left_jets[0], right_jets[0], mixed_jets[0]
    for spin in range(2):
        ds, dds = d[spin], dd[spin]
        left_rho[spin] = _ao_bilinear(lp, ds, p) + _ao_bilinear(p, ds, lp)
        right_rho[spin] = (
            _ao_bilinear(rp, ds, p) + _ao_bilinear(p, ds, rp) + _ao_bilinear(p, dds, p)
        )
        mixed_rho[spin] = (
            _ao_bilinear(mp, ds, p)
            + _ao_bilinear(lp, dds, p)
            + _ao_bilinear(lp, ds, rp)
            + _ao_bilinear(rp, ds, lp)
            + _ao_bilinear(p, dds, lp)
            + _ao_bilinear(p, ds, mp)
        )
        if family == "lda":
            continue
        assert left_gradient is not None
        assert right_gradient is not None
        assert mixed_gradient is not None
        for axis in range(3):
            row = axis + 1
            pk = jets[row]
            lpk = left_jets[row]
            rpk = right_jets[row]
            mpk = mixed_jets[row]
            left_gradient[spin, :, axis] = (
                _ao_bilinear(lpk, ds, p)
                + _ao_bilinear(pk, ds, lp)
                + _ao_bilinear(lp, ds, pk)
                + _ao_bilinear(p, ds, lpk)
            )
            right_gradient[spin, :, axis] = (
                _ao_bilinear(rpk, ds, p)
                + _ao_bilinear(pk, ds, rp)
                + _ao_bilinear(rp, ds, pk)
                + _ao_bilinear(p, ds, rpk)
                + _ao_bilinear(pk, dds, p)
                + _ao_bilinear(p, dds, pk)
            )
            mixed_gradient[spin, :, axis] = (
                _ao_bilinear(mpk, ds, p)
                + _ao_bilinear(lpk, dds, p)
                + _ao_bilinear(lpk, ds, rp)
                + _ao_bilinear(rpk, ds, lp)
                + _ao_bilinear(pk, dds, lp)
                + _ao_bilinear(pk, ds, mp)
                + _ao_bilinear(mp, ds, pk)
                + _ao_bilinear(lp, dds, pk)
                + _ao_bilinear(lp, ds, rpk)
                + _ao_bilinear(rp, ds, lpk)
                + _ao_bilinear(p, dds, lpk)
                + _ao_bilinear(p, ds, mpk)
            )

    left = {"rho": immutable(left_rho)}
    right = {"rho": immutable(right_rho)}
    mixed = {"rho": immutable(mixed_rho)}
    if family == "gga":
        assert left_gradient is not None
        assert right_gradient is not None
        assert mixed_gradient is not None
        base_gradient = reference["gradient"]
        left["gradient"] = immutable(left_gradient)
        right["gradient"] = immutable(right_gradient)
        mixed["gradient"] = immutable(mixed_gradient)
        pairs = ((0, 0), (0, 1), (1, 1))
        left["sigma"] = immutable(
            np.stack(
                [
                    np.sum(
                        left_gradient[a] * base_gradient[b]
                        + base_gradient[a] * left_gradient[b],
                        axis=1,
                    )
                    for a, b in pairs
                ]
            )
        )
        right["sigma"] = immutable(
            np.stack(
                [
                    np.sum(
                        right_gradient[a] * base_gradient[b]
                        + base_gradient[a] * right_gradient[b],
                        axis=1,
                    )
                    for a, b in pairs
                ]
            )
        )
        mixed["sigma"] = immutable(
            np.stack(
                [
                    np.sum(
                        mixed_gradient[a] * base_gradient[b]
                        + left_gradient[a] * right_gradient[b]
                        + right_gradient[a] * left_gradient[b]
                        + base_gradient[a] * mixed_gradient[b],
                        axis=1,
                    )
                    for a, b in pairs
                ]
            )
        )
    return left, right, mixed


@dataclass(frozen=True)
class XCMixedDirectional:
    """Four audited pieces of one semilocal XC Hessian bilinear."""

    mixed_measure: float
    left_measure_right_feature: float
    right_measure_left_feature: float
    feature_mixed: float

    @property
    def total(self) -> float:
        return (
            self.mixed_measure
            + self.left_measure_right_feature
            + self.right_measure_left_feature
            + self.feature_mixed
        )


@dataclass(frozen=True, eq=False)
class GeometryPartials:
    """Explicit gradients at fixed D, normalization parameters and mask.

    ``centers`` is [atom,xyz], ``points`` is [point,xyz], and ``weights`` is
    [point]. Supplied physical motion contracts with these sources once each.
    They exclude orbital response, other energies and stationary/Pulay terms.
    """

    centers: np.ndarray
    points: np.ndarray
    weights: np.ndarray

    def directional(
        self, *, centers: typing.Any, points: typing.Any, weights: typing.Any
    ) -> typing.Any:
        """Contract independently supplied basis, grid and measure motion."""
        return float(
            np.sum(self.centers * immutable(centers, shape=self.centers.shape))
            + np.sum(self.points * immutable(points, shape=self.points.shape))
            + np.sum(self.weights * immutable(weights, shape=self.weights.shape))
        )


class ContractionProgram:
    """Generate minimal tile E/V, density response or explicit geometric partials.

    Arrays are bounded by the caller's tile. Potentials/responses retain
    functional-spin layout (one channel for unpolarized, two for polarized);
    integration adapters own conversion back to the caller's density layout.
    The diagnostic scalar evaluator is replaceable by the matching native
    program without changing any scientific contraction.
    """

    def __init__(self, spec: typing.Any, observable: typing.Any = "potential") -> None:
        self.contract = DiscreteEnergyContract(spec, DerivativeRequest(observable))
        self.program = build_program(
            spec,
            order=self.contract.request.scalar_order,
            outputs=self.contract.scalar_outputs,
        )
        ingredients = self.contract.ingredients
        self.coefficients = coefficient_program(
            spec.spin,
            ingredients.family,
            kinetic=ingredients.family == "mgga",
        )
        self.response_coefficients = (
            coefficient_program(spec.spin, ingredients.family, response=True)
            if observable == "response"
            else None
        )
        self.jet_pullback = (
            jet_pullback_program(ingredients.family)
            if observable == "geometry"
            else None
        )

    @property
    def spec(self) -> typing.Any:
        return self.contract.functional

    def _feature_ingredients(self) -> tuple[str, ...]:
        family = self.contract.ingredients.family
        return (
            ("rho",)
            if family == "lda"
            else ("rho", "gradient", "sigma", "tau")
            if family == "mgga"
            else ("rho", "gradient", "sigma")
        )

    def features(self, jets: typing.Any, density: typing.Any) -> typing.Any:
        """Perform only the ingredient reductions declared by this functional."""
        return density_features(jets, density, ingredients=self._feature_ingredients())

    def _features_from_spin_densities(
        self, jets: typing.Any, density: typing.Any
    ) -> typing.Any:
        """Consume a two-spin density already normalized by the enclosing endpoint."""
        return _density_features_from_spin_densities(
            jets, density, ingredients=self._feature_ingredients()
        )

    def scalar_values(self, features: typing.Any) -> typing.Any:
        """Evaluate only declared roots; keep their derivative labels explicit."""
        raw = self.program.evaluate(_pack(self.spec, features))
        return dict(zip(self.program.outputs, raw, strict=True))

    def _gradient(self, rows: typing.Any, npoint: typing.Any) -> typing.Any:
        propagated = getattr(rows, "feature_gradient", None)
        if propagated is not None:
            if (
                not isinstance(propagated, np.ndarray)
                or propagated.dtype != np.float64
                or propagated.shape != (len(self.spec.features), npoint)
                or not propagated.flags.c_contiguous
                or not np.isfinite(propagated).all()
            ):
                raise ValueError("invalid propagated XC feature-gradient layout")
            return propagated
        result = np.zeros((len(self.spec.features), npoint))
        for index in self.contract.ingredients.feature_indices:
            result[index] = rows[(index,)]
        return result

    def geometry_feature_direction(
        self,
        jets: typing.Any,
        density: typing.Any,
        *,
        ao_atoms: typing.Any,
        center_motion: typing.Any,
        point_motion: typing.Any,
        delta_density: typing.Any = None,
    ) -> typing.Any:
        """Prepare the common LDA/GGA AO-feature geometry direction.

        This keeps AO motion and feature-chain-rule algebra under one compiler
        owner while allowing either the generated scalar Graph or an external
        SCF-domain point provider to supply the actual XC potential derivatives.
        """
        if self.contract.request.observable != "geometry":
            raise ValueError(
                "geometry feature direction requires a geometry contraction"
            )
        family = self.contract.ingredients.family
        if family not in ("lda", "gga"):
            raise UnsupportedXC("XC geometry JVP supports LDA/GGA only")
        raw_jets = immutable(jets)
        ingredient_order = self.contract.ingredients.ao_order
        required = len(jet_indices(ingredient_order + 1))
        if (
            raw_jets.ndim != 3
            or raw_jets.shape[0] not in (4, 10, 20)
            or raw_jets.shape[0] < required
        ):
            raise ValueError("XC geometry JVP requires AO jets through order+1")
        npoint, nao = raw_jets.shape[1:]
        points = immutable(point_motion, shape=(npoint, 3))
        centers = immutable(center_motion)
        if centers.ndim != 2 or centers.shape[1:] != (3,):
            raise ValueError("XC geometry JVP requires [atom,3] center motion")
        atoms = np.asarray(ao_atoms)
        if (
            atoms.shape != (nao,)
            or atoms.dtype.kind not in "iu"
            or np.any(atoms < 0)
            or (atoms.size and np.max(atoms) >= len(centers))
        ):
            raise ValueError("XC geometry JVP requires one valid atom per AO")
        d = spin_densities(density, nao)
        if self.spec.spin == "unpolarized" and not np.array_equal(d[0], d[1]):
            raise UnsupportedXC("unpolarized contractions require equal spin matrices")
        if delta_density is None:
            delta_density = np.zeros_like(np.asarray(density, dtype=float))
        dd = spin_densities(delta_density, nao)
        if self.spec.spin == "unpolarized" and not np.array_equal(dd[0], dd[1]):
            raise UnsupportedXC(
                "unpolarized geometry JVP requires equal spin directions"
            )

        base_count = len(jet_indices(ingredient_order))
        base_jets = raw_jets[:base_count]
        directional_jets = directional_ao_jets(
            raw_jets,
            ingredient_order,
            ao_atoms=atoms,
            point_motion=points,
            center_motion=centers,
        )
        features = self._features_from_spin_densities(base_jets, d)
        direction = _geometry_feature_direction(
            features, base_jets, directional_jets, d, dd, family
        )
        return base_jets, directional_jets, features, direction

    def potential_geometry_directional(
        self,
        jets: typing.Any,
        density: typing.Any,
        weights: typing.Any,
        *,
        ao_atoms: typing.Any,
        center_motion: typing.Any,
        point_motion: typing.Any,
        weight_motion: typing.Any,
        delta_density: typing.Any = None,
    ) -> typing.Any:
        """Differentiate the LDA/GGA XC AO potential along one geometry direction.

        Geometry and quadrature motion are explicit inputs. An optional density
        direction is accepted for validation/composition, while a stationary
        nuclear RHS normally passes zero and lets the shared CPKS operator own
        induced density-to-Fock physics.
        """
        raw_jets = immutable(jets)
        npoint = raw_jets.shape[1] if raw_jets.ndim == 3 else -1
        weights = immutable(weights, shape=(npoint,))
        dweights = immutable(weight_motion, shape=(npoint,))
        base_jets, directional_jets, features, direction = (
            self.geometry_feature_direction(
                raw_jets,
                density,
                ao_atoms=ao_atoms,
                center_motion=center_motion,
                point_motion=point_motion,
                delta_density=delta_density,
            )
        )
        second = ContractionProgram(self.spec, "response")
        rows = second.scalar_values(features)
        v = second._gradient(rows, npoint)
        packed = _pack(self.spec, direction)
        dv = np.zeros_like(v)
        indices = second.contract.ingredients.feature_indices
        for i in indices:
            for j in indices:
                dv[i] += rows[(min(i, j), max(i, j))] * packed[j]
        response_coefficients = second.response_coefficients
        if response_coefficients is None:
            raise RuntimeError("response coefficient program is unavailable")
        coefficients = self.coefficients.evaluate(
            _functional_gradient(self.spec, features), v
        )
        directional_coefficients = response_coefficients.evaluate(
            _functional_gradient(self.spec, features),
            v,
            delta_gradient=_functional_gradient(self.spec, direction),
            delta_v=dv,
        )
        return assemble_coefficients_directional(
            base_jets,
            directional_jets,
            coefficients,
            directional_coefficients,
            weights,
            dweights,
        )

    def mixed_geometry_directional(
        self,
        jets: typing.Any,
        density: typing.Any,
        weights: typing.Any,
        *,
        ao_atoms: typing.Any,
        left_centers: typing.Any,
        left_points: typing.Any,
        left_weights: typing.Any,
        right_centers: typing.Any,
        right_points: typing.Any,
        right_weights: typing.Any,
        mixed_weights: typing.Any,
        delta_density: typing.Any = None,
    ) -> typing.Any:
        """Contract one LDA/GGA XC Hessian bilinear without a Hessian tensor.

        The left direction is geometric. The right direction may additionally
        carry the CPKS density response. The chain rule differentiates the left
        directional XC energy with respect to the right direction using
        generated XC feature gradients/Hessians, analytic AO-jet JVPs and
        externally supplied first/mixed quadrature motions. It owns no CPKS
        solve and no molecular-grid motion policy.
        """
        if self.contract.request.observable != "geometry":
            raise ValueError("mixed geometry requires a geometry contraction")
        family = self.contract.ingredients.family
        if family not in ("lda", "gga"):
            raise UnsupportedXC("mixed XC geometry supports semilocal LDA/GGA only")
        raw_jets = immutable(jets)
        ingredient_order = self.contract.ingredients.ao_order
        required = len(jet_indices(ingredient_order + 2))
        if (
            raw_jets.ndim != 3
            or raw_jets.shape[0] not in (10, 20)
            or raw_jets.shape[0] < required
        ):
            raise ValueError("mixed XC geometry requires AO jets through order+2")
        npoint, nao = raw_jets.shape[1:]
        weights = immutable(weights, shape=(npoint,))
        left_points = immutable(left_points, shape=(npoint, 3))
        right_points = immutable(right_points, shape=(npoint, 3))
        left_weights = immutable(left_weights, shape=(npoint,))
        right_weights = immutable(right_weights, shape=(npoint,))
        mixed_weights = immutable(mixed_weights, shape=(npoint,))
        left_centers = immutable(left_centers)
        right_centers = immutable(right_centers, shape=left_centers.shape)
        if left_centers.ndim != 2 or left_centers.shape[1:] != (3,):
            raise ValueError("mixed XC geometry requires [atom,3] center directions")
        atoms = np.asarray(ao_atoms)
        if (
            atoms.shape != (nao,)
            or atoms.dtype.kind not in "iu"
            or np.any(atoms < 0)
            or (atoms.size and np.max(atoms) >= len(left_centers))
        ):
            raise ValueError("mixed XC geometry requires one valid atom per AO")

        d = spin_densities(density, nao)
        if self.spec.spin == "unpolarized" and not np.array_equal(d[0], d[1]):
            raise UnsupportedXC("unpolarized contractions require equal spin matrices")
        if delta_density is None:
            delta_density = np.zeros_like(np.asarray(density, dtype=float))
        dd = spin_densities(delta_density, nao)
        if self.spec.spin == "unpolarized" and not np.array_equal(dd[0], dd[1]):
            raise UnsupportedXC(
                "unpolarized mixed geometry requires equal spin density directions"
            )

        base_count = len(jet_indices(ingredient_order))
        extended_count = len(jet_indices(ingredient_order + 1))
        left_extended = directional_ao_jets(
            raw_jets,
            ingredient_order + 1,
            ao_atoms=atoms,
            point_motion=left_points,
            center_motion=left_centers,
        )
        left_jets = left_extended[:base_count]
        right_jets = directional_ao_jets(
            raw_jets,
            ingredient_order,
            ao_atoms=atoms,
            point_motion=right_points,
            center_motion=right_centers,
        )
        mixed_jets = directional_ao_jets(
            left_extended[:extended_count],
            ingredient_order,
            ao_atoms=atoms,
            point_motion=right_points,
            center_motion=right_centers,
        )
        base_jets = raw_jets[:base_count]
        features = self._features_from_spin_densities(base_jets, d)
        left, right, mixed = _geometry_feature_directions(
            features,
            base_jets,
            left_jets,
            right_jets,
            mixed_jets,
            d,
            dd,
            family,
        )

        second = ContractionProgram(self.spec, "response")
        rows = second.scalar_values(features)
        gradient = second._gradient(rows, npoint)
        left_packed = _pack(self.spec, left)
        right_packed = _pack(self.spec, right)
        mixed_packed = _pack(self.spec, mixed)
        indices = second.contract.ingredients.feature_indices
        active = list(indices)
        left_energy = np.sum(gradient[active] * left_packed[active], axis=0)
        right_energy = np.sum(gradient[active] * right_packed[active], axis=0)
        mixed_feature_energy = np.sum(gradient[active] * mixed_packed[active], axis=0)
        for i in indices:
            for j in indices:
                mixed_feature_energy += (
                    left_packed[i] * rows[(min(i, j), max(i, j))] * right_packed[j]
                )

        result = XCMixedDirectional(
            mixed_measure=float(mixed_weights @ rows[()]),
            left_measure_right_feature=float(left_weights @ right_energy),
            right_measure_left_feature=float(right_weights @ left_energy),
            feature_mixed=float(weights @ mixed_feature_energy),
        )
        if not np.isfinite(result.total):
            raise ArithmeticError("nonfinite mixed XC geometry contraction")
        return result

    def potential_tile(
        self, jets: typing.Any, features: typing.Any, weights: typing.Any
    ) -> typing.Any:
        """Consume complete-density features from a validated collocation owner."""
        if self.contract.request.observable != "potential":
            raise ValueError("potential tile requires a potential request")
        rows = self.scalar_values(features)
        return self.potential_from_rows(jets, features, weights, rows)

    def potential_from_rows(
        self,
        jets: typing.Any,
        features: typing.Any,
        weights: typing.Any,
        rows: typing.Any,
    ) -> typing.Any:
        """Assemble the unchanged potential after an explicitly planned scalar call."""
        if self.contract.request.observable != "potential":
            raise ValueError("potential rows require a potential request")
        weights = immutable(weights, shape=(jets.shape[1],))
        # The packed scalar owner may be donated to the coefficient producer.
        # Consume the energy row before that ownership transfer overwrites it.
        energy = _weighted_energy(weights, rows[()])
        v = self._gradient(rows, jets.shape[1])
        gradient = _functional_gradient(self.spec, features)
        output_owner = getattr(rows, "coefficient_output_owner", None)
        coefficients = (
            self.coefficients.evaluate(gradient, v)
            if output_owner is None
            else self.coefficients.evaluate(gradient, v, output_owner=output_owner)
        )
        return {
            "energy": energy,
            "potential": assemble_coefficients(jets, coefficients, weights),
            "electrons": immutable(features["rho"] @ weights),
        }

    def _tile_inputs(
        self, jets: typing.Any, weights: typing.Any
    ) -> tuple[np.ndarray, np.ndarray]:
        jets, weights = immutable(jets), immutable(weights)
        required = len(jet_indices(self.contract.ao_order))
        if (
            jets.ndim != 3
            or jets.shape[0] not in (1, 4, 10, 20)
            or jets.shape[0] < required
            or weights.shape != (jets.shape[1],)
        ):
            raise ValueError("XC contraction requires its declared AO/point domain")
        return jets, weights

    def _evaluate_spin_densities(
        self,
        jets: np.ndarray,
        density: typing.Any,
        weights: np.ndarray,
        *,
        delta_density: typing.Any = None,
        ao_atoms: typing.Any = None,
        natom: typing.Any = None,
    ) -> typing.Any:
        """Evaluate after an enclosing boundary has normalized spin densities once."""
        observable = self.contract.request.observable
        if observable != "response" and delta_density is not None:
            raise ValueError("density direction requires a response request")
        if observable != "geometry" and (ao_atoms is not None or natom is not None):
            raise ValueError("AO-center map requires a geometric request")
        features = self._features_from_spin_densities(jets, density)
        if observable == "potential":
            return self.potential_tile(jets, features, weights)
        rows = self.scalar_values(features)
        result = {
            "energy": _weighted_energy(weights, rows[()]),
            "electrons": immutable(features["rho"] @ weights),
        }
        if observable == "energy":
            return result
        v = self._gradient(rows, jets.shape[1])
        gradient = _functional_gradient(self.spec, features)
        if observable == "response":
            requested = ("rho",) if gradient is None else ("rho", "gradient")
            delta = _response_features(
                features,
                _density_features_from_spin_densities(
                    jets, delta_density, ingredients=requested
                ),
            )
            direction = _pack(self.spec, delta)
            dv = np.zeros_like(v)
            indices = self.contract.ingredients.feature_indices
            for i in indices:
                for j in indices:
                    dv[i] += rows[(min(i, j), max(i, j))] * direction[j]
            response_coefficients = self.response_coefficients
            if response_coefficients is None:
                raise RuntimeError("response coefficient program is unavailable")
            response = response_coefficients.evaluate(
                gradient,
                v,
                delta_gradient=_functional_gradient(self.spec, delta),
                delta_v=dv,
            )
            result["response"] = assemble_coefficients(jets, response, weights)
        else:
            coefficients = self.coefficients.evaluate(gradient, v)
            result["geometry"] = self._geometry(
                jets, density, weights, coefficients, rows[()], ao_atoms, natom
            )
        return result

    def _evaluate_prevalidated_density(
        self,
        jets: typing.Any,
        density: typing.Any,
        weights: typing.Any,
        *,
        delta_density: typing.Any = None,
        ao_atoms: typing.Any = None,
        natom: typing.Any = None,
    ) -> typing.Any:
        """Internal tile path for density owners validated by a prepared endpoint."""
        jets, weights = self._tile_inputs(jets, weights)
        return self._evaluate_spin_densities(
            jets,
            density,
            weights,
            delta_density=delta_density,
            ao_atoms=ao_atoms,
            natom=natom,
        )

    def evaluate(
        self,
        jets: typing.Any,
        density: typing.Any,
        weights: typing.Any,
        *,
        delta_density: typing.Any = None,
        ao_atoms: typing.Any = None,
        natom: typing.Any = None,
    ) -> typing.Any:
        """Return exactly the requested observable for a complete-density tile.

        Geometry requires one extra spatial jet and an explicit AO-to-atom
        map. Response directions may be indefinite but must be real symmetric;
        cross-spin Hessian terms are preserved before AO assembly.
        """
        jets, weights = self._tile_inputs(jets, weights)
        d = spin_densities(density, jets.shape[2])
        if self.spec.spin == "unpolarized" and not np.array_equal(d[0], d[1]):
            raise UnsupportedXC("unpolarized contractions require equal spin matrices")
        observable = self.contract.request.observable
        if observable != "response" and delta_density is not None:
            raise ValueError("density direction requires a response request")
        dd = None
        if observable == "response":
            dd = spin_densities(delta_density, jets.shape[2])
            if self.spec.spin == "unpolarized" and not np.array_equal(dd[0], dd[1]):
                raise UnsupportedXC(
                    "unpolarized response requires equal spin directions"
                )
        return self._evaluate_spin_densities(
            jets,
            d,
            weights,
            delta_density=dd,
            ao_atoms=ao_atoms,
            natom=natom,
        )

    def geometry_from_cartesian_coefficients(
        self,
        jets: typing.Any,
        density: typing.Any,
        weights: typing.Any,
        energy: typing.Any,
        rho_coefficients: typing.Any,
        gradient_coefficients: typing.Any = None,
        kinetic_coefficients: typing.Any = None,
        *,
        ao_atoms: typing.Any,
        natom: typing.Any,
    ) -> typing.Any:
        """Apply generated AO-jet pullback to an audited point differential.

        The point provider supplies dE/drho_s, dE/dgrad(rho_s), and for
        meta-GGA the already contracted kinetic AO coefficient vtau_s/2.
        This matches the native r2SCAN point ABI and the compact coefficient
        generated by coefficient_program. RKS averages the two spin kinetic
        coefficients because Da=Db=D/2; UKS consumes each spin coefficient once.
        """
        if self.contract.request.observable != "geometry":
            raise ValueError("Cartesian coefficient pullback requires geometry")
        jets, weights = immutable(jets), immutable(weights)
        required = len(jet_indices(self.contract.ao_order))
        if (
            jets.ndim != 3
            or jets.shape[0] not in (1, 4, 10, 20)
            or jets.shape[0] < required
            or weights.shape != (jets.shape[1],)
        ):
            raise ValueError("XC pullback requires its declared AO/point domain")
        d = spin_densities(density, jets.shape[2])
        if self.spec.spin == "unpolarized" and not np.array_equal(d[0], d[1]):
            raise UnsupportedXC("unpolarized contractions require equal spin matrices")
        npoint = jets.shape[1]
        energy = immutable(energy, shape=(npoint,))
        rho = immutable(rho_coefficients, shape=(2, npoint))
        arrays = [energy, rho]
        family = self.contract.ingredients.family
        gradient = None
        tau = None
        if family in ("gga", "mgga"):
            gradient = immutable(gradient_coefficients, shape=(2, npoint, 3))
            arrays.append(gradient)
        elif gradient_coefficients is not None:
            raise ValueError("LDA Cartesian pullback does not consume gradients")
        if family == "mgga":
            tau = immutable(kinetic_coefficients, shape=(2, npoint))
            arrays.append(tau)
        elif kinetic_coefficients is not None:
            raise ValueError("LDA/GGA Cartesian pullback does not consume kinetic tau")
        if not all(np.isfinite(value).all() for value in arrays):
            raise ValueError("nonfinite XC Cartesian coefficient")

        if self.spec.spin == "polarized":
            coefficients = {"rho": rho}
            if gradient is not None:
                coefficients["gradient"] = gradient
            if tau is not None:
                coefficients["tau"] = tau
        else:
            # RKS stores D=Da+Db. The native kinetic coefficients already
            # include tau_s's 1/2 AO-bilinear factor, so only the spin split
            # Da=Db=D/2 remains here.
            coefficients = {"rho": immutable(0.5 * (rho[0] + rho[1]))[None]}
            if gradient is not None:
                coefficients["gradient"] = immutable(0.5 * (gradient[0] + gradient[1]))[
                    None
                ]
            if tau is not None:
                coefficients["tau"] = immutable(0.5 * (tau[0] + tau[1]))[None]
        return self._geometry(jets, d, weights, coefficients, energy, ao_atoms, natom)

    def _geometry(
        self,
        jets: typing.Any,
        density: typing.Any,
        weights: typing.Any,
        coefficients: typing.Any,
        energy: typing.Any,
        ao_atoms: typing.Any,
        natom: typing.Any,
    ) -> typing.Any:
        """Pull back compact AO bilinears, then split translation sources.

        A normalized AO depends on r-R_A; ordinary spatial jets therefore
        supply point motion with positive sign and its own center motion with
        negative sign. Weight derivatives are e_xc, without a second weight.
        """
        atoms = np.asarray(ao_atoms)
        if (
            type(natom) is not int
            or natom < 1
            or atoms.shape != (jets.shape[2],)
            or atoms.dtype.kind not in "iu"
            or np.any(atoms < 0)
            or np.any(atoms >= natom)
        ):
            raise ValueError("geometry requires a valid integer AO-to-atom map")
        order = self.contract.ingredients.ao_order
        domain = jet_indices(order)
        lookup = {axis: i for i, axis in enumerate(jet_indices(self.contract.ao_order))}
        d = density if self.spec.spin == "polarized" else density.sum(axis=0)[None]
        pullback = np.zeros((len(domain), *jets.shape[1:]))
        # Every spin consumes these jet contractions synchronously. A single
        # owned panel avoids restacking separately allocated products on each
        # spin without changing the FP64 per-jet GEMM definition.
        work = np.empty((len(domain), *jets.shape[1:]), dtype=np.float64)
        for spin in range(len(d)):
            for jet_index in range(len(domain)):
                np.matmul(jets[jet_index], d[spin], out=work[jet_index])
            weighted = {"rho": weights * coefficients["rho"][spin]}
            if order:
                weighted["gradient"] = weights[:, None] * coefficients["gradient"][spin]
            if "tau" in coefficients:
                weighted["tau"] = weights * coefficients["tau"][spin]
            jet_pullback = self.jet_pullback
            if jet_pullback is None:
                raise RuntimeError("geometry pullback program is unavailable")
            pullback += jet_pullback.evaluate(weighted, work)
        centers = np.zeros((natom, 3))
        points = np.zeros((jets.shape[1], 3))
        # The directional AO panel is consumed by the current Cartesian
        # component before advancing to the next axis.
        panel = np.zeros(jets.shape[1:])
        for k in range(3):
            panel.fill(0.0)
            for j, axis in enumerate(domain):
                shifted = list(axis)
                shifted[k] += 1
                panel += pullback[j] * jets[lookup[tuple(shifted)]]
            points[:, k] = panel.sum(axis=1)
            np.add.at(centers[:, k], atoms, -panel.sum(axis=0))
        return GeometryPartials(
            immutable(centers), immutable(points), immutable(energy)
        )


class ExternalPointContraction(ContractionProgram):
    """Reuse semilocal AO contractions with externally owned point derivatives.

    The external provider owns the scalar XC energy and feature derivatives.
    This adapter owns only the existing ingredient reductions, Cartesian
    coefficient contraction, and AO/grid geometry pullback.  It therefore does
    not build or authorize a scalar functional Graph on its own.
    """

    def __init__(self, spec: typing.Any, observable: typing.Any = "geometry") -> None:
        if observable not in ("energy", "potential", "geometry"):
            raise UnsupportedXC(
                "external point contractions support energy, potential, or geometry"
            )
        self.contract = DiscreteEnergyContract(spec, DerivativeRequest(observable))
        ingredients = self.contract.ingredients
        self.coefficients = coefficient_program(
            spec.spin,
            ingredients.family,
            kinetic=ingredients.family == "mgga",
        )
        self.response_coefficients = None
        self.jet_pullback = (
            jet_pullback_program(ingredients.family)
            if observable == "geometry"
            else None
        )

    def scalar_values(self, features: typing.Any) -> typing.Any:
        raise RuntimeError(
            "external point contraction requires provider-owned scalar derivatives"
        )

    def pack_features(self, features: typing.Any) -> typing.Any:
        """Return the canonical feature-major scalar ABI for an external provider."""
        return _pack(self.spec, features)

    def mixed_geometry_from_rks_cartesian_coefficients(
        self,
        jets: typing.Any,
        density: typing.Any,
        weights: typing.Any,
        *,
        ao_atoms: typing.Any,
        left_centers: typing.Any,
        left_points: typing.Any,
        left_weights: typing.Any,
        right_centers: typing.Any,
        right_points: typing.Any,
        right_weights: typing.Any,
        mixed_weights: typing.Any,
        energy: typing.Any,
        rho_coefficients: typing.Any,
        directional_rho_coefficients: typing.Any,
        gradient_coefficients: typing.Any = None,
        directional_gradient_coefficients: typing.Any = None,
        delta_density: typing.Any = None,
    ) -> typing.Any:
        """Contract an RKS XC Hessian bilinear from provider-owned point data.

        The external point owner supplies the SCF-domain energy, Cartesian
        density/gradient potential coefficients, and their derivative along the
        right geometry+density direction. AO/grid mixed motion stays under the
        shared contraction owner. This is sufficient for an LDA/GGA Hessian
        bilinear; no third XC derivative or scalar-Graph substitution is needed.
        """
        if self.contract.request.observable != "geometry":
            raise ValueError("mixed RKS geometry requires a geometry contraction")
        if self.spec.spin != "unpolarized":
            raise UnsupportedXC("external mixed RKS geometry requires unpolarized XC")
        family = self.contract.ingredients.family
        if family not in ("lda", "gga"):
            raise UnsupportedXC("external mixed RKS geometry supports LDA/GGA only")

        raw_jets = immutable(jets)
        ingredient_order = self.contract.ingredients.ao_order
        required = len(jet_indices(ingredient_order + 2))
        if (
            raw_jets.ndim != 3
            or raw_jets.shape[0] not in (10, 20)
            or raw_jets.shape[0] < required
        ):
            raise ValueError("mixed RKS geometry requires AO jets through order+2")
        npoint, nao = raw_jets.shape[1:]
        weights = immutable(weights, shape=(npoint,))
        left_points = immutable(left_points, shape=(npoint, 3))
        right_points = immutable(right_points, shape=(npoint, 3))
        left_weights = immutable(left_weights, shape=(npoint,))
        right_weights = immutable(right_weights, shape=(npoint,))
        mixed_weights = immutable(mixed_weights, shape=(npoint,))
        left_centers = immutable(left_centers)
        right_centers = immutable(right_centers, shape=left_centers.shape)
        if left_centers.ndim != 2 or left_centers.shape[1:] != (3,):
            raise ValueError("mixed RKS geometry requires [atom,3] center directions")
        atoms = np.asarray(ao_atoms)
        if (
            atoms.shape != (nao,)
            or atoms.dtype.kind not in "iu"
            or np.any(atoms < 0)
            or (atoms.size and np.max(atoms) >= len(left_centers))
        ):
            raise ValueError("mixed RKS geometry requires one valid atom per AO")

        d = spin_densities(density, nao)
        if not np.array_equal(d[0], d[1]):
            raise UnsupportedXC("mixed RKS geometry requires an equal-spin density")
        if delta_density is None:
            delta_density = np.zeros_like(np.asarray(density, dtype=float))
        dd = spin_densities(delta_density, nao)
        if not np.array_equal(dd[0], dd[1]):
            raise UnsupportedXC(
                "mixed RKS geometry requires an equal-spin density direction"
            )

        base_count = len(jet_indices(ingredient_order))
        extended_count = len(jet_indices(ingredient_order + 1))
        left_extended = directional_ao_jets(
            raw_jets,
            ingredient_order + 1,
            ao_atoms=atoms,
            point_motion=left_points,
            center_motion=left_centers,
        )
        left_jets = left_extended[:base_count]
        right_jets = directional_ao_jets(
            raw_jets,
            ingredient_order,
            ao_atoms=atoms,
            point_motion=right_points,
            center_motion=right_centers,
        )
        mixed_jets = directional_ao_jets(
            left_extended[:extended_count],
            ingredient_order,
            ao_atoms=atoms,
            point_motion=right_points,
            center_motion=right_centers,
        )
        base_jets = raw_jets[:base_count]
        features = self.features(base_jets, d)
        left, right, mixed = _geometry_feature_directions(
            features,
            base_jets,
            left_jets,
            right_jets,
            mixed_jets,
            d,
            dd,
            family,
        )

        energy = immutable(energy, shape=(npoint,))
        rho = immutable(rho_coefficients, shape=(npoint,))
        drho = immutable(directional_rho_coefficients, shape=(npoint,))
        arrays = [energy, rho, drho]
        gradient = dgradient = None
        if family == "gga":
            gradient = immutable(gradient_coefficients, shape=(npoint, 3))
            dgradient = immutable(directional_gradient_coefficients, shape=(npoint, 3))
            arrays.extend((gradient, dgradient))
        elif (
            gradient_coefficients is not None
            or directional_gradient_coefficients is not None
        ):
            raise ValueError("LDA mixed RKS geometry does not consume gradients")
        if not all(np.isfinite(value).all() for value in arrays):
            raise ValueError("nonfinite external RKS XC coefficient")

        def feature_energy(
            value: typing.Any,
            rho_value: np.ndarray,
            gradient_value: np.ndarray | None,
        ) -> np.ndarray:
            result = rho_value * value["rho"].sum(axis=0)
            if family == "gga":
                assert gradient_value is not None
                result = result + np.sum(
                    gradient_value * value["gradient"].sum(axis=0), axis=1
                )
            return result

        left_energy = feature_energy(left, rho, gradient)
        right_energy = feature_energy(right, rho, gradient)
        mixed_feature_energy = feature_energy(mixed, rho, gradient)
        mixed_feature_energy += feature_energy(left, drho, dgradient)

        result = XCMixedDirectional(
            mixed_measure=float(mixed_weights @ energy),
            left_measure_right_feature=float(left_weights @ right_energy),
            right_measure_left_feature=float(right_weights @ left_energy),
            feature_mixed=float(weights @ mixed_feature_energy),
        )
        if not np.isfinite(result.total):
            raise ArithmeticError("nonfinite external mixed RKS XC contraction")
        return result

    def geometry_from_feature_rows(
        self,
        jets: typing.Any,
        density: typing.Any,
        weights: typing.Any,
        features: typing.Any,
        rows: typing.Any,
        *,
        ao_atoms: typing.Any,
        natom: typing.Any,
    ) -> typing.Any:
        """Convert provider-owned feature derivatives through the common pullback."""
        if self.contract.request.observable != "geometry":
            raise ValueError("feature-row geometry requires a geometry request")
        npoint = np.asarray(jets).shape[1]
        v = self._gradient(rows, npoint)
        compact = self.coefficients.evaluate(
            _functional_gradient(self.spec, features), v
        )
        rho = compact["rho"]
        gradient = compact.get("gradient")
        tau = compact.get("tau")
        if self.spec.spin == "unpolarized":
            rho = np.repeat(rho, 2, axis=0)
            if gradient is not None:
                gradient = np.repeat(gradient, 2, axis=0)
            if tau is not None:
                tau = np.repeat(tau, 2, axis=0)
        return self.geometry_from_cartesian_coefficients(
            jets,
            density,
            weights,
            rows[()],
            rho,
            gradient,
            tau,
            ao_atoms=ao_atoms,
            natom=natom,
        )
