// Generated by tools/generate_method_manifest.py from methods/public_methods.json.
// Native function pointers remain registry-owned; this file owns public identity/capability facts.
#ifndef VIBEQC_METHODS_GENERATED_METHOD_MANIFEST_HPP
#define VIBEQC_METHODS_GENERATED_METHOD_MANIFEST_HPP

#include <array>
#include <cstdint>
#include <string_view>

#include "vibeqc/vibeqc.h"

// clang-format off
namespace vibeqc::methods::generated {

enum class PublicProvider : std::uint8_t { Reserved, Hf, Mp2, Rccsd, Dft };

struct MethodManifestEntry {
  std::string_view name;
  vibeqc_method method;
  vibeqc_method_family family;
  vibeqc_property_flags properties;
  bool supports_batch;
  PublicProvider provider;
  std::string_view unavailable_reason;
};

inline constexpr std::array<MethodManifestEntry, 15> kMethodManifest{{
    {"rhf", VIBEQC_METHOD_RHF, VIBEQC_METHOD_FAMILY_HARTREE_FOCK, VIBEQC_PROPERTY_ENERGY | VIBEQC_PROPERTY_FORCES, true, PublicProvider::Hf, ""},
    {"uhf", VIBEQC_METHOD_UHF, VIBEQC_METHOD_FAMILY_HARTREE_FOCK, VIBEQC_PROPERTY_ENERGY | VIBEQC_PROPERTY_FORCES, true, PublicProvider::Hf, ""},
    {"wb97m-v", VIBEQC_METHOD_WB97M_V, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, 0, false, PublicProvider::Reserved, "method has no executable provider registration"},
    {"rccsd(t)", VIBEQC_METHOD_RCCSD_T, VIBEQC_METHOD_FAMILY_COUPLED_CLUSTER, 0, false, PublicProvider::Reserved, "method has no executable provider registration"},
    {"mp2", VIBEQC_METHOD_MP2, VIBEQC_METHOD_FAMILY_PERTURBATION, VIBEQC_PROPERTY_ENERGY | VIBEQC_PROPERTY_FORCES, true, PublicProvider::Mp2, ""},
    {"lda-rks", VIBEQC_METHOD_LDA_RKS, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"pbe-rks", VIBEQC_METHOD_PBE_RKS, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"lda-uks", VIBEQC_METHOD_LDA_UKS, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"pbe-uks", VIBEQC_METHOD_PBE_UKS, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"r2scan-rks", VIBEQC_METHOD_R2SCAN_RKS, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"r2scan-uks", VIBEQC_METHOD_R2SCAN_UKS, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"rccsd", VIBEQC_METHOD_RCCSD, VIBEQC_METHOD_FAMILY_COUPLED_CLUSTER, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Rccsd, ""},
    {"pbe0-rks", VIBEQC_METHOD_PBE0_RKS, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"pbe0-uks", VIBEQC_METHOD_PBE0_UKS, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
    {"pbe-d4-rks", VIBEQC_METHOD_PBE_D4_RKS, VIBEQC_METHOD_FAMILY_DENSITY_FUNCTIONAL, VIBEQC_PROPERTY_ENERGY, true, PublicProvider::Dft, ""},
}};

inline constexpr const MethodManifestEntry* find_method(
    std::string_view name) noexcept {
  for (const auto& method : kMethodManifest)
    if (method.name == name) return &method;
  return nullptr;
}

inline constexpr const MethodManifestEntry* find_method(
    vibeqc_method value) noexcept {
  for (const auto& method : kMethodManifest)
    if (method.method == value) return &method;
  return nullptr;
}

}  // namespace vibeqc::methods::generated
// clang-format on

#endif
