"""Emit the source-reusing low-angular MD Coulomb consumer.

The integral compiler owns reciprocal Hermite contraction and its bounded CUDA
schedule. Native SCF owns admission, storage, density lifetime and stream policy.
Radial mathematics is not duplicated: both orientations call the existing
fill_coulomb owner once, retaining independent output-specific screening.
"""

from __future__ import annotations

_SOURCE = r"""
#pragma once

#include <algorithm>
#include <cmath>

#include "runtime/cuda_resources.cuh"
#include "scf/cuda/coulomb_auxiliary.cuh"
#include "scf/cuda/direct_md_j.hpp"
#include "scf/cuda/md_hermite_index.cuh"

// Generated by the integral compiler; keep radial recurrence ownership native.
namespace generativeqc::scf::cuda_execution {
namespace {

constexpr unsigned kMdReciprocalTile = 8;

/** Preserve the incumbent's output-specific density error allowance. Sharing
 * a source never makes an omitted reciprocal orientation authoritative. */
__device__ bool md_reciprocal_admitted(MdJView md, const MdJPair& output,
                                      const MdJPair& input, double screening) {
  const auto output_index = static_cast<std::size_t>(&output - md.pairs);
  const auto input_index = static_cast<std::size_t>(&input - md.pairs);
  if (md.minimum_bounds[output_index] * md.minimum_bounds[input_index] < screening)
    return false;
  const double density_bound = md.density_bounds[input_index];
  const double contribution = __dmul_ru(
      __dmul_ru(md.maximum_bounds[output_index], md.maximum_bounds[input_index]), density_bound);
  const double allowance =
      __ddiv_rd(fmin(screening, kMdJDensityErrorCap), double(md.pair_count));
  return density_bound != 0.0 && contribution >= allowance;
}

/** Contract both consumers of one canonical radial source. Reversing the
 * source displacement multiplies R_(a+b) by (-1)^(a+b), so the reverse
 * density sign (-1)^a reduces to the same (-1)^b coefficient as the forward
 * consumer. Boys/Hermite evaluation remains owned by fill_coulomb. */
template <unsigned BraAngular, unsigned KetAngular>
__device__ void md_reciprocal_contract(const MdJPrimitive& bra, const MdJPrimitive& ket,
                                      MdJView md, bool forward, bool reverse,
                                      double* bra_potential, double* ket_potential) {
  CoulombAuxiliary<double, BraAngular + KetAngular> auxiliary;
  const double rho = bra.exponent * ket.exponent / (bra.exponent + ket.exponent);
  fill_coulomb<BraAngular + KetAngular>(rho, bra.product, ket.product, auxiliary);
  const double prefactor =
      2.0 * pow(kPi, 2.5) / (bra.exponent * ket.exponent * sqrt(bra.exponent + ket.exponent));
  for (unsigned bra_component = 0; bra_component < md_j_hermite_count(BraAngular);
       ++bra_component) {
    const auto bra_angular = md_hermite_angular(BraAngular, bra_component);
    double forward_value = 0.0;
    for (unsigned ket_component = 0; ket_component < md_j_hermite_count(KetAngular);
         ++ket_component) {
      const auto ket_angular = md_hermite_angular(KetAngular, ket_component);
      const double sign = (ket_angular.x + ket_angular.y + ket_angular.z) & 1U ? -1.0 : 1.0;
      const double radial = auxiliary.at(0, bra_angular.x + ket_angular.x,
                                        bra_angular.y + ket_angular.y,
                                        bra_angular.z + ket_angular.z);
      if (forward)
        forward_value += sign * md.density[ket.hermite_offset + ket_component] * radial;
      if (reverse)
        ket_potential[ket_component] +=
            sign * md.density[bra.hermite_offset + bra_component] * radial;
    }
    bra_potential[bra_component] = prefactor * forward_value;
  }
  for (unsigned ket_component = 0; ket_component < md_j_hermite_count(KetAngular);
       ++ket_component)
    ket_potential[ket_component] *= prefactor;
}

/** A fixed worker inventory consumes each unordered low-angular primitive
 * tile once. Shared tile reductions limit global publication to one atomic
 * per primitive/Hermite component, rather than one per primitive product.
 * No retained queue, complete integral tensor or additional allocation exists. */
template <unsigned BraAngular, unsigned KetAngular, bool CountWork>
__global__ void md_j_reciprocal_potential(MdJView md, std::size_t system_begin,
                                         std::size_t system_end, double screening) {
  static_assert(BraAngular <= 2 && KetAngular <= 2);
  constexpr unsigned bra_components = md_j_hermite_count(BraAngular);
  constexpr unsigned ket_components = md_j_hermite_count(KetAngular);
  __shared__ double bra_terms[kMdReciprocalTile][kMdReciprocalTile][bra_components];
  __shared__ double ket_terms[kMdReciprocalTile][kMdReciprocalTile][ket_components];
  __shared__ unsigned long long tile_index, bra_tile, ket_tile;
  const auto bra_count = md.class_offsets[BraAngular + 1] - md.class_offsets[BraAngular];
  const auto ket_count = md.class_offsets[KetAngular + 1] - md.class_offsets[KetAngular];
  const auto bra_tiles = (bra_count + kMdReciprocalTile - 1) / kMdReciprocalTile;
  const auto ket_tiles = (ket_count + kMdReciprocalTile - 1) / kMdReciprocalTile;
  const auto tile_count = BraAngular == KetAngular
                              ? bra_tiles * (bra_tiles + 1ULL) / 2
                              : bra_tiles * ket_tiles;
  const unsigned bra_slot = threadIdx.x / kMdReciprocalTile;
  const unsigned ket_slot = threadIdx.x % kMdReciprocalTile;
  unsigned long long roots = 0, forwards = 0, reverses = 0;
  while (true) {
    if (threadIdx.x == 0) {
      tile_index = atomicAdd(md.source_cursor, 1ULL);
      if constexpr (BraAngular == KetAngular) {
        ket_tile = static_cast<unsigned long long>((sqrt(8.0 * tile_index + 1.0) - 1.0) * 0.5);
        while (ket_tile * (ket_tile + 1ULL) / 2 > tile_index) --ket_tile;
        while ((ket_tile + 1ULL) * (ket_tile + 2ULL) / 2 <= tile_index) ++ket_tile;
        bra_tile = tile_index - ket_tile * (ket_tile + 1ULL) / 2;
      } else {
        bra_tile = tile_index / ket_tiles;
        ket_tile = tile_index % ket_tiles;
      }
    }
    __syncthreads();
    if (tile_index >= tile_count) {
      if constexpr (CountWork) {
        for (unsigned stride = 16; stride; stride /= 2) {
          roots += __shfl_down_sync(0xffffffff, roots, stride);
          forwards += __shfl_down_sync(0xffffffff, forwards, stride);
          reverses += __shfl_down_sync(0xffffffff, reverses, stride);
        }
        if (threadIdx.x % 32 == 0) {
          constexpr auto forward_angular = 5 * BraAngular + KetAngular;
          constexpr auto reverse_angular = 5 * KetAngular + BraAngular;
          constexpr auto summands = bra_components * ket_components;
          atomicAdd(&md.work_counts->uniform_roots[forward_angular], roots);
          atomicAdd(&md.work_counts->uniform_directions[forward_angular], forwards);
          atomicAdd(&md.work_counts->uniform_directions[reverse_angular], reverses);
          atomicAdd(&md.work_counts->uniform_summands[forward_angular], forwards * summands);
          atomicAdd(&md.work_counts->uniform_summands[reverse_angular], reverses * summands);
        }
      }
      return;
    }
    const auto bra_position = bra_tile * kMdReciprocalTile + bra_slot;
    const auto ket_position = ket_tile * kMdReciprocalTile + ket_slot;
    double bra_values[bra_components]{};
    double ket_values[ket_components]{};
    if (bra_position < bra_count && ket_position < ket_count &&
        (BraAngular != KetAngular || bra_position <= ket_position)) {
      const auto& bra = md.primitives[md.ordered_primitives[
          md.class_offsets[BraAngular] + bra_position]];
      const auto& ket = md.primitives[md.ordered_primitives[
          md.class_offsets[KetAngular] + ket_position]];
      const auto& bra_pair = md.pairs[bra.pair];
      const auto& ket_pair = md.pairs[ket.pair];
      if (bra_pair.system >= system_begin && bra_pair.system < system_end &&
          bra_pair.system == ket_pair.system) {
        const bool forward = md_reciprocal_admitted(md, bra_pair, ket_pair, screening);
        const bool reverse = (BraAngular != KetAngular || bra_position != ket_position) &&
                             md_reciprocal_admitted(md, ket_pair, bra_pair, screening);
        if (forward || reverse)
          md_reciprocal_contract<BraAngular, KetAngular>(
              bra, ket, md, forward, reverse, bra_values, ket_values);
        if constexpr (CountWork) {
          roots += forward || reverse;
          forwards += forward;
          reverses += reverse;
        }
      }
    }
    for (unsigned component = 0; component < bra_components; ++component)
      bra_terms[bra_slot][ket_slot][component] = bra_values[component];
    for (unsigned component = 0; component < ket_components; ++component)
      ket_terms[bra_slot][ket_slot][component] = ket_values[component];
    __syncthreads();
    // Angular-two tiles have 80 output components, more than the 64 source
    // lanes. Stride the full publication domain instead of dropping its tail.
    for (unsigned output_index = threadIdx.x;
         output_index < kMdReciprocalTile * bra_components; output_index += blockDim.x) {
      const unsigned output_slot = output_index / bra_components;
      const unsigned component = output_index % bra_components;
      const auto position = bra_tile * kMdReciprocalTile + output_slot;
      if (position < bra_count) {
        double value = 0.0;
        for (unsigned source_slot = 0; source_slot < kMdReciprocalTile; ++source_slot)
          value += bra_terms[output_slot][source_slot][component];
        const auto& primitive = md.primitives[md.ordered_primitives[
            md.class_offsets[BraAngular] + position]];
        if (value != 0.0) atomicAdd(md.potential + primitive.hermite_offset + component, value);
      }
    }
    for (unsigned output_index = threadIdx.x;
         output_index < kMdReciprocalTile * ket_components; output_index += blockDim.x) {
      const unsigned output_slot = output_index / ket_components;
      const unsigned component = output_index % ket_components;
      const auto position = ket_tile * kMdReciprocalTile + output_slot;
      if (position < ket_count) {
        double value = 0.0;
        for (unsigned source_slot = 0; source_slot < kMdReciprocalTile; ++source_slot)
          value += ket_terms[source_slot][output_slot][component];
        const auto& primitive = md.primitives[md.ordered_primitives[
            md.class_offsets[KetAngular] + position]];
        if (value != 0.0) atomicAdd(md.potential + primitive.hermite_offset + component, value);
      }
    }
    __syncthreads();
  }
}

template <unsigned BraAngular, unsigned KetAngular>
void launch_md_reciprocal_potential(cudaStream_t stream, MdJView md, std::size_t begin,
                                   std::size_t end, double screening) {
  const auto bra_tiles = (md.class_offsets[BraAngular + 1] - md.class_offsets[BraAngular] +
                          kMdReciprocalTile - 1) / kMdReciprocalTile;
  const auto ket_tiles = (md.class_offsets[KetAngular + 1] - md.class_offsets[KetAngular] +
                          kMdReciprocalTile - 1) / kMdReciprocalTile;
  if (!bra_tiles || !ket_tiles) return;
  const auto tile_count = BraAngular == KetAngular
                              ? bra_tiles * (bra_tiles + 1ULL) / 2
                              : bra_tiles * ket_tiles;
  runtime::cuda_resource_check(
      cudaMemsetAsync(md.source_cursor, 0, sizeof(unsigned long long), stream));
  const auto workers = static_cast<unsigned>(std::min<std::size_t>(4096, tile_count));
  if (md.work_counts)
    md_j_reciprocal_potential<BraAngular, KetAngular, true>
        <<<workers, kMdReciprocalTile * kMdReciprocalTile, 0, stream>>>(md, begin, end, screening);
  else
    md_j_reciprocal_potential<BraAngular, KetAngular, false>
        <<<workers, kMdReciprocalTile * kMdReciprocalTile, 0, stream>>>(md, begin, end, screening);
  runtime::cuda_resource_check(cudaPeekAtLastError());
}

}  // namespace
}  // namespace generativeqc::scf::cuda_execution
"""


def emit_md_j_reciprocal_header() -> str:
    """Return deterministic FP64 CUDA; no runtime import or GPU probe is needed."""
    return _SOURCE.lstrip("\n")
