"""Compiler ownership and bounded-source contracts for reciprocal MD Coulomb."""

from pathlib import Path

from generativeqc_compiler.integral.md_j_reciprocal_cuda import (
    emit_md_j_reciprocal_header,
)

ROOT = Path(__file__).resolve().parents[2]


def test_reciprocal_consumer_reuses_the_existing_radial_owner() -> None:
    """The second orientation must not introduce a second Boys/ERI recurrence."""
    source = emit_md_j_reciprocal_header()
    assert source == emit_md_j_reciprocal_header()
    assert source.startswith("#pragma once\n")
    assert source.count("fill_coulomb<BraAngular + KetAngular>") == 1
    assert "(-1)^(a+b)" in source
    assert "__dmul_ru(" in source
    assert "static_assert(BraAngular <= 2 && KetAngular <= 2)" in source
    assert source.count("output_index += blockDim.x") == 2
    assert "std::min<std::size_t>(4096, tile_count)" in source
    assert "cudaMalloc" not in source


def test_reciprocal_generation_is_a_build_dependency() -> None:
    """Both unified and split native CUDA builds consume generated bytes."""
    generated = (ROOT / "cmake/GenerativeQCGeneratedSources.cmake").read_text()
    cuda = (ROOT / "cmake/GenerativeQCCuda.cmake").read_text()
    native = (ROOT / "src/scf/cuda/direct_md_j.cu").read_text()
    assert "generate_md_j_reciprocal.py" in generated
    assert cuda.count("GENERATIVEQC_MD_J_RECIPROCAL_HEADER") == 2
    assert '#include "generated_md_j_reciprocal.cuh"' in native
    assert not (ROOT / "src/scf/cuda/md_reciprocal_potential.cuh").exists()
