"""Compiler-owned production derivative lowering for molecular D4(BJ)-EEQ.

The native EEQ and fixed-charge D4 evaluators are custom scientific primitives:
they publish the primitive Jacobian dq/dR and partial derivatives
(dE/dR)_q and dE/dq. This module owns the only production composition of those
derivatives. The older complete C++ evaluator remains an independent
qualification oracle and is intentionally not called by production runtime.
"""

from __future__ import annotations

from dataclasses import dataclass

from vibeqc_compiler.common.provenance import canonical_hash


@dataclass(frozen=True)
class D4EEQDerivativeLowering:
    """Canonical chain-rule lowering around the EEQ implicit charge primitive."""

    version: str = "d4-eeq-production-derivative-v1"
    charge_jacobian_layout: str = "coordinate-major"
    equation: str = "dE_dR=partial_E_partial_R+(dq_dR@dE_dq)"

    def to_payload(self) -> dict[str, str]:
        return {
            "version": self.version,
            "charge_jacobian_layout": self.charge_jacobian_layout,
            "equation": self.equation,
            "charge_primitive": "eeq2019-implicit-solve",
            "dispersion_primitive": "d4-bj-eeq-fixed-charge",
        }

    @property
    def identity(self) -> str:
        return canonical_hash(self.to_payload())

    def emit_cpp(self) -> str:
        """Emit the production lowering; primitive formulas stay provider-owned."""

        source = """// Generated by tools/generate_d4_derivative.py; do not edit.
// Compiler identity: __IDENTITY__
#pragma once

#include <cstddef>

#include "dft/dispersion/d4_eeq.hpp"

#if defined(__CUDACC__)
#define VIBEQC_D4_GENERATED_HD __host__ __device__
#else
#define VIBEQC_D4_GENERATED_HD
#endif

namespace vibeqc::generated::d4 {

inline constexpr char kDerivativeLoweringIdentity[] = "__IDENTITY__";

VIBEQC_D4_GENERATED_HD inline dft::dispersion::D4Status compose_eeq_gradient(
    int n, const double* dqdr, const double* dedq,
    const double* explicit_gradient, double* gradient) {
  using namespace dft::dispersion;
  if (n < 0 || n > kD4MaximumAtoms || !dqdr || !dedq || !explicit_gradient || !gradient)
    return D4Status::invalid_argument;
  const std::size_t count = static_cast<std::size_t>(n);
  for (int coordinate = 0; coordinate < 3 * n; ++coordinate) {
    double value = explicit_gradient[coordinate];
    for (int atom = 0; atom < n; ++atom)
      value += dqdr[static_cast<std::size_t>(coordinate) * count + atom] * dedq[atom];
    if (!eeq_detail::finite(value)) return D4Status::numerical_failure;
    gradient[coordinate] = value;
  }
  return D4Status::success;
}

VIBEQC_D4_GENERATED_HD inline dft::dispersion::D4Status evaluate_production_d4_eeq(
    int n, const std::int32_t* z, const double* xyz, double total_charge,
    const dft::dispersion::D4Parameters& parameters,
    dft::dispersion::D4EEQProfile profile,
    dft::dispersion::D4Tables d4_tables,
    dft::dispersion::EEQTables eeq_tables,
    double* workspace, std::size_t workspace_size,
    double* energy, double* gradient, double* charges) {
  using namespace dft::dispersion;
  if (n < 0 || n > kD4MaximumAtoms) return D4Status::unsupported;
  if (profile != D4EEQProfile::standard && profile != D4EEQProfile::r2scan3c)
    return D4Status::unsupported;
  const bool r2scan = profile == D4EEQProfile::r2scan3c;
  if (parameters.reference_model != D4ReferenceModel::eeq ||
      fabs(parameters.ga - (r2scan ? 2.0 : 3.0)) > 1.0e-15 ||
      fabs(parameters.gc - (r2scan ? 1.0 : 2.0)) > 1.0e-15)
    return D4Status::unsupported;
  if (workspace_size < complete_d4_eeq_workspace_elements(n) || !workspace ||
      !energy || !gradient || (n && (!charges || !z || !xyz)))
    return D4Status::invalid_argument;

  const std::size_t count = static_cast<std::size_t>(n);
  double* eeq_workspace = workspace;
  double* d4_workspace = eeq_workspace + eeq2019_workspace_elements(n);
  double* q = d4_workspace + d4_workspace_elements(n);
  double* dqdr = q + count;
  double* dedq = dqdr + 3 * count * count;
  double* explicit_gradient = dedq + count;

  auto status = evaluate_eeq2019_with_tables(
      n, z, xyz, total_charge, eeq_tables, eeq_workspace,
      eeq2019_workspace_elements(n), q, dqdr);
  if (status != D4Status::success) return status;

  double candidate_energy[2] = {0.0, 0.0};
  status = evaluate_d4_fixed_charge(
      n, z, xyz, q, parameters, d4_tables, d4_workspace,
      d4_workspace_elements(n), candidate_energy, explicit_gradient, dedq);
  if (status != D4Status::success) return status;

  // Compiler-owned VJP: J_q(R)^T * dE/dq plus the fixed-charge partial.
  status = compose_eeq_gradient(n, dqdr, dedq, explicit_gradient, explicit_gradient);
  if (status != D4Status::success) return status;

  // Transactional publication: no partial result escapes primitive or VJP failure.
  energy[0] = candidate_energy[0];
  energy[1] = candidate_energy[1];
  for (int coordinate = 0; coordinate < 3 * n; ++coordinate)
    gradient[coordinate] = explicit_gradient[coordinate];
  for (int atom = 0; atom < n; ++atom) charges[atom] = q[atom];
  return D4Status::success;
}

}  // namespace vibeqc::generated::d4
#undef VIBEQC_D4_GENERATED_HD
"""
        return source.replace("__IDENTITY__", self.identity)


PRODUCTION_D4_EEQ_DERIVATIVE = D4EEQDerivativeLowering()
