// Generated by tools/generate_method_manifest.py from methods/public_methods.json.
// Do not edit by hand; ABI ids are explicit manifest data and must never be renumbered implicitly.
#ifndef VIBEQC_GENERATED_METHOD_IDS_H
#define VIBEQC_GENERATED_METHOD_IDS_H

#include <stdint.h>

// clang-format off
typedef int32_t vibeqc_method;
enum {
  VIBEQC_METHOD_RHF = 1,
  VIBEQC_METHOD_UHF = 2,
  VIBEQC_METHOD_WB97M_V = 3,
  VIBEQC_METHOD_RCCSD_T = 4,
  VIBEQC_METHOD_MP2 = 5,
  VIBEQC_METHOD_LDA_RKS = 6,
  VIBEQC_METHOD_PBE_RKS = 7,
  VIBEQC_METHOD_LDA_UKS = 8,
  VIBEQC_METHOD_PBE_UKS = 9,
  VIBEQC_METHOD_R2SCAN_RKS = 10,
  VIBEQC_METHOD_R2SCAN_UKS = 11,
  VIBEQC_METHOD_RCCSD = 12,
  VIBEQC_METHOD_PBE0_RKS = 13,
  VIBEQC_METHOD_PBE0_UKS = 14,
  VIBEQC_METHOD_PBE_D4_RKS = 15
};
// clang-format on

#endif
